## 标量

In [1]:
import torch
x = torch.tensor(3.0)
y = torch.tensor(2.0)
x+y,x*y,x/y,x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

## 向量
$$
\mathbf{x}=\left[ \begin{array}{c}
	x_1\\
	x_2\\
	\vdots\\
	x_n\\
\end{array} \right] 
$$


In [2]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [3]:
x[3]

tensor(3)

In [4]:
len(x)

4

> 当用张量表示一个向量（只有一个轴）时，我们也可以通过.shape属性访问向量的长度。形状（shape）是一
个元素组，列出了张量沿每个轴的长度（维数）。对于只有一个轴的张量，形状只有一个元素。

In [5]:
x.shape

torch.Size([4])

## 矩阵
$$
\boldsymbol{A}_{m\times n}=\left[ \begin{array}{l}
	a_{11}&		a_{12}&		\cdots&		a_{1n}\\
	a_{21}&		a_{22}&		\cdots&		a_{2n}\\
	\vdots&		\vdots&		\ddots&		\vdots\\
	a_{m1}&		a_{m2}&		\cdots&		a_{mn}\\
\end{array} \right] 
$$


In [6]:
A = torch.arange(20).reshape(5,4)

In [7]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [8]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [9]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

## 张量
就像向量是标量的推广，矩阵是向量的推广一样，我们可以构建具有更多轴的数据结构。张量（本小节中的“张量”指代数对象）是描述具有任意数量轴的$n$维数组的通用方法。例如，向量是一阶张量，矩阵是二阶张量。张量用特殊字体的大写字母表示（例如，$\mathbf{X}$、$\mathbf{V}$和$\mathbf{Z}$），它们的索引机制（例如$x_{ijk}$和$[\mathbf{X}]_{1,2i-1,3}$）与矩阵类似。

当我们开始处理图像时，张量将变得更加重要，图像以$n$维数组形式出现，其中3个轴对应于高度、宽度，以及一个通道（channel）轴，用于表示颜色通道（红色、绿色和蓝色）。现在先将高阶张量暂放一边，而是专注于学习其基础知识。

In [10]:
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## 张量算法的基本性质
> 标量、向量、矩阵和任意数量轴的张量（本小节中的“张量”指代数对象）有一些实用的属性。例如，从按元素操作的定义中可以注意到，任何按元素的一元运算都不会改变其操作数的形状。同样，给定具有相同形状的任意两个张量，任何按元素二元运算的结果都将是相同形状的张量。例如，将两个相同形状的矩阵相加，会在这两个矩阵上执行元素加法。

In [11]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
B = A.clone()
A,A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

矩阵的乘法是Hadamard积:
$$
\mathbf{A}\odot \mathbf{B}=\left[ \begin{matrix}
	a_{11}b_{11}&		a_{12}b_{12}&		\dots&		a_{1n}b_{1n}\\
	a_{21}b_{21}&		a_{22}b_{22}&		\dots&		a_{2n}b_{2n}\\
	\vdots&		\vdots&		\ddots&		\vdots\\
	a_{m1}b_{m1}&		a_{m2}b_{m2}&		\dots&		a_{mn}b_{mn}\\
\end{matrix} \right] .
$$


In [12]:
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

将张量乘以或加上一个标量不会改变张量的形状，其中张量的每个元素都将与标量相加或相乘

In [13]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

## 降维
计算向量中元素的和:
$$
sum=\sum_{i=1}^d{x_i}
$$


In [14]:
x = torch.arange(4,dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

矩阵中的张量和
$$
sum=\sum_{i=1}^m{\sum_{j=1}^n{a_{ij}}}
$$


In [15]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

默认情况下，调用求和函数会沿所有的轴降低张量的维度，使它变为一个标量。我们还可以指定张量沿哪一个轴来通过求和降低维度。以矩阵为例，为了通过求和所有行的元素来降维（轴0），可以在调用函数时指定axis=0。由于输入矩阵沿0轴降维以生成输出向量，因此输入轴0的维数在输出形状中消失。

In [16]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0

tensor([40., 45., 50., 55.])

In [17]:
import torch

# 我们熟悉的三维张量
X = torch.arange(24).reshape(2, 3, 4)
print("原始张量 X (形状: {}):".format(X.shape))
print(X)
print("\n" + "="*50 + "\n")

# 我们要研究的操作
result = X.sum(axis=[0, 1])

print("X.sum(axis=[0, 1]) 的结果 (形状: {}):".format(result.shape))
print(result)

原始张量 X (形状: torch.Size([2, 3, 4])):
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


X.sum(axis=[0, 1]) 的结果 (形状: torch.Size([4])):
tensor([60, 66, 72, 78])


In [18]:
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [19]:
t = X.sum(axis=0)
print(t)
q = t.sum(axis=0)
print(q)

tensor([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]])
tensor([60, 66, 72, 78])


In [20]:
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [21]:
X.sum(axis=[0,2])

tensor([ 60,  92, 124])

In [22]:
X.sum(axis=[1])

tensor([[12, 15, 18, 21],
        [48, 51, 54, 57]])

In [23]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

求平均

In [24]:
A.mean(),A.sum()/A.numel()

(tensor(9.5000), tensor(9.5000))

In [25]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

非降维求和 \
但是，有时在调用函数来计算总和或均值时保持轴数不变会很有用。

In [31]:
A,A.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 torch.Size([5, 4]))

In [27]:
sum_A = A.sum(axis=1,keepdim=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [28]:
A.sum(axis=1)

tensor([ 6., 22., 38., 54., 70.])

In [34]:
B=torch.arange(24).reshape(4,3,2)
B

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]])

In [35]:
B.sum(axis=2)

tensor([[ 1,  5,  9],
        [13, 17, 21],
        [25, 29, 33],
        [37, 41, 45]])

In [36]:
B.sum(axis=2,keepdim=True)

tensor([[[ 1],
         [ 5],
         [ 9]],

        [[13],
         [17],
         [21]],

        [[25],
         [29],
         [33]],

        [[37],
         [41],
         [45]]])

In [40]:
B.sum(axis=1),B.sum(axis=1,keepdim=True)

(tensor([[ 6,  9],
         [24, 27],
         [42, 45],
         [60, 63]]),
 tensor([[[ 6,  9]],
 
         [[24, 27]],
 
         [[42, 45]],
 
         [[60, 63]]]))

In [38]:
B[0]

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [39]:
B[0,0]

tensor([0, 1])

In [41]:
B.sum(axis=0)

tensor([[36, 40],
        [44, 48],
        [52, 56]])

In [42]:
B.sum(axis=0,keepdim=True)

tensor([[[36, 40],
         [44, 48],
         [52, 56]]])

如果我们想沿某个轴计算A元素的累积总和，比如`axis=0`（按行计算），可以调用`cumsum`函数。此函数不会沿任何轴降低输入张量的维度

In [43]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [44]:
B

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]])

## 点积
给定两个向量$\mathbf{x}, \mathbf{y} \in \mathbb{R}^d$，它们的点积 (dot product) $\mathbf{x}^\top\mathbf{y}$ (或$\langle\mathbf{x}, \mathbf{y}\rangle$) 是相同位置的按元素乘积的和：
$$\mathbf{x}^\top\mathbf{y} = \sum_{i=1}^d x_i y_i$$。

In [50]:
x = torch.arange(4,dtype=torch.float32)
x

tensor([0., 1., 2., 3.])

In [51]:
y = torch.ones(4,dtype=torch.float32)
y

tensor([1., 1., 1., 1.])

In [52]:
torch.dot(x,y)

tensor(6.)

In [53]:
x*y

tensor([0., 1., 2., 3.])

In [54]:
torch.sum(x*y)

tensor(6.)

## 矩阵——向量积

现在我们知道如何计算点积，可以开始理解矩阵-向量积 (matrix-vector product)。回顾分别在 (2.3.2)和 (2.3.1)中定义的矩阵 $\mathbf{A} \in \mathbb{R}^{m \times n}$ 和向量 $\mathbf{x} \in \mathbb{R}^n$。让我们将矩阵 $\mathbf{A}$ 用它的行向量表示：

$$
\mathbf{A} = \begin{bmatrix} \mathbf{a}_1^\top \\ \mathbf{a}_2^\top \\ \vdots \\ \mathbf{a}_m^\top \end{bmatrix},
$$

其中每个 $\mathbf{a}_i^\top \in \mathbb{R}^n$ 都是行向量，表示矩阵的第 $i$ 行。矩阵向量积 $\mathbf{Ax}$ 是一个长度为 $m$ 的列向量，其第 $i$ 个元素是点积 $\mathbf{a}_i^\top \mathbf{x}$:

$$
\mathbf{Ax} = \begin{bmatrix} \mathbf{a}_1^\top \\ \mathbf{a}_2^\top \\ \vdots \\ \mathbf{a}_m^\top \end{bmatrix} \mathbf{x} = \begin{bmatrix} \mathbf{a}_1^\top \mathbf{x} \\ \mathbf{a}_2^\top \mathbf{x} \\ \vdots \\ \mathbf{a}_m^\top \mathbf{x} \end{bmatrix}.
$$


### 举例说明

这个公式说明，一个矩阵和一个向量相乘，其结果向量的每一个元素，都是由矩阵的对应行向量与那个向量做点积得到的。

我们来看一个具体的例子。

假设我们有矩阵 $\mathbf{A}$ 和向量 $\mathbf{x}$：

$$
\mathbf{A} = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}, \quad \mathbf{x} = \begin{bmatrix} 7 \\ 8 \\ 9 \end{bmatrix}
$$

这里，矩阵 $\mathbf{A}$ 是一个 $2 \times 3$ 的矩阵，向量 $\mathbf{x}$ 是一个 $3 \times 1$ 的向量。

根据公式，我们可以把矩阵 $\mathbf{A}$ 看作是由两个行向量 $\mathbf{a}_1^\top$ 和 $\mathbf{a}_2^\top$ 堆叠而成的：

*   第一个行向量是 $\mathbf{a}_1^\top = [1, 2, 3]$
*   第二个行向量是 $\mathbf{a}_2^\top = [4, 5, 6]$

现在，我们来计算矩阵-向量积 $\mathbf{Ax}$。结果会是一个 $2 \times 1$ 的向量，它的每个元素是 $\mathbf{A}$ 的行向量和 $\mathbf{x}$ 的点积：

$$
\mathbf{Ax} = \begin{bmatrix} \mathbf{a}_1^\top \mathbf{x} \\ \mathbf{a}_2^\top \mathbf{x} \end{bmatrix} = \begin{bmatrix} [1, 2, 3] \begin{bmatrix} 7 \\ 8 \\ 9 \end{bmatrix} \\ [4, 5, 6] \begin{bmatrix} 7 \\ 8 \\ 9 \end{bmatrix} \end{bmatrix}
$$

我们分别计算这两个点积：

1.  第一个元素：$\mathbf{a}_1^\top \mathbf{x} = (1 \times 7) + (2 \times 8) + (3 \times 9) = 7 + 16 + 27 = 50$
2.  第二个元素：$\mathbf{a}_2^\top \mathbf{x} = (4 \times 7) + (5 \times 8) + (6 \times 9) = 28 + 40 + 54 = 122$

所以，最终的结果是：

$$
\mathbf{Ax} = \begin{bmatrix} 50 \\ 122 \end{bmatrix}
$$

这个例子清晰地展示了如何将矩阵的每一行与向量进行点积，从而得到最终的向量结果。

In [55]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [56]:
A.shape,x.shape

(torch.Size([5, 4]), torch.Size([4]))

In [57]:
torch.mv(A,x)

tensor([ 14.,  38.,  62.,  86., 110.])

## 矩阵乘法

在掌握点积和矩阵-向量积的知识后，那么矩阵-矩阵乘法 (matrix-matrix multiplication) 应该很简单。

假设有两个矩阵 $\mathbf{A} \in \mathbb{R}^{n \times k}$ 和 $\mathbf{B} \in \mathbb{R}^{k \times m}$:
$$
\mathbf{A} = \begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1k} \\
a_{21} & a_{22} & \cdots & a_{2k} \\
\vdots & \vdots & \ddots & \vdots \\
a_{n1} & a_{n2} & \cdots & a_{nk}
\end{bmatrix},
\quad
\mathbf{B} = \begin{bmatrix}
b_{11} & b_{12} & \cdots & b_{1m} \\
b_{21} & b_{22} & \cdots & b_{2m} \\
\vdots & \vdots & \ddots & \vdots \\
b_{k1} & b_{k2} & \cdots & b_{km}
\end{bmatrix}.
$$
用行向量 $\mathbf{a}_i^\top \in \mathbb{R}^k$ 表示矩阵 $\mathbf{A}$ 的第 $i$ 行，并让列向量 $\mathbf{b}_j \in \mathbb{R}^k$ 作为矩阵 $\mathbf{B}$ 的第 $j$ 列。要生成矩阵积 $\mathbf{C} = \mathbf{AB}$，最简单的方法是考虑 $\mathbf{A}$ 的行向量和 $\mathbf{B}$ 的列向量：
$$
\mathbf{A} = \begin{bmatrix}
\mathbf{a}_1^\top \\
\mathbf{a}_2^\top \\
\vdots \\
\mathbf{a}_n^\top
\end{bmatrix},
\quad
\mathbf{B} = \begin{bmatrix}
\mathbf{b}_1 & \mathbf{b}_2 & \cdots & \mathbf{b}_m
\end{bmatrix}.
$$
当我们简单地将每个元素 $c_{ij}$ 计算为点积 $\mathbf{a}_i^\top \mathbf{b}_j$:
$$
\mathbf{C} = \mathbf{AB} = \begin{bmatrix}
\mathbf{a}_1^\top \\
\mathbf{a}_2^\top \\
\vdots \\
\mathbf{a}_n^\top
\end{bmatrix}
\begin{bmatrix}
\mathbf{b}_1 & \mathbf{b}_2 & \cdots & \mathbf{b}_m
\end{bmatrix} = \begin{bmatrix}
\mathbf{a}_1^\top \mathbf{b}_1 & \mathbf{a}_1^\top \mathbf{b}_2 & \cdots & \mathbf{a}_1^\top \mathbf{b}_m \\
\mathbf{a}_2^\top \mathbf{b}_1 & \mathbf{a}_2^\top \mathbf{b}_2 & \cdots & \mathbf{a}_2^\top \mathbf{b}_m \\
\vdots & \vdots & \ddots & \vdots \\
\mathbf{a}_n^\top \mathbf{b}_1 & \mathbf{a}_n^\top \mathbf{b}_2 & \cdots & \mathbf{a}_n^\top \mathbf{b}_m
\end{bmatrix}.
$$
我们可以将矩阵-矩阵乘法 $\mathbf{AB}$ 看作简单地执行 $m$ 次矩阵-向量积，并将结果拼接在一起，形成一个 $n \times m$ 矩阵。在下面的代码中，我们在A和B上执行矩阵乘法。这里的A是一个5行4列的矩阵，B是一个4行3列的矩阵。两者相乘后，我们得到了一个5行3列的矩阵。

***

### 举例说明

这个公式的核心思想是：结果矩阵 $\mathbf{C}$ 中第 $i$ 行、第 $j$ 列的元素 $c_{ij}$，是由第一个矩阵 $\mathbf{A}$ 的第 $i$ 行与第二个矩阵 $\mathbf{B}$ 的第 $j$ 列进行点积运算得到的。

我们来看一个具体的例子。

假设我们有两个矩阵 $\mathbf{A}$ (2x3) 和 $\mathbf{B}$ (3x2)：

$$
\mathbf{A} = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}, \quad \mathbf{B} = \begin{bmatrix} 7 & 8 \\ 9 & 10 \\ 11 & 12 \end{bmatrix}
$$

要计算 $\mathbf{C} = \mathbf{AB}$，结果 $\mathbf{C}$ 将会是一个 $2 \times 2$ 的矩阵。

首先，我们把 $\mathbf{A}$ 分解为行向量：
*   $\mathbf{A}$ 的第1行: $\mathbf{a}_1^\top = [1, 2, 3]$
*   $\mathbf{A}$ 的第2行: $\mathbf{a}_2^\top = [4, 5, 6]$

然后，把 $\mathbf{B}$ 分解为列向量：
*   $\mathbf{B}$ 的第1列: $\mathbf{b}_1 = \begin{bmatrix} 7 \\ 9 \\ 11 \end{bmatrix}$
*   $\mathbf{B}$ 的第2列: $\mathbf{b}_2 = \begin{bmatrix} 8 \\ 10 \\ 12 \end{bmatrix}$

现在，我们根据公式 $c_{ij} = \mathbf{a}_i^\top \mathbf{b}_j$ 来计算 $\mathbf{C}$ 的四个元素：

1.  **$c_{11}$ (C的第一行第一列)** = $\mathbf{A}$ 的第1行 $\cdot$ $\mathbf{B}$ 的第1列 = $\mathbf{a}_1^\top \mathbf{b}_1$
    $c_{11} = (1 \times 7) + (2 \times 9) + (3 \times 11) = 7 + 18 + 33 = 58$

2.  **$c_{12}$ (C的第一行第二列)** = $\mathbf{A}$ 的第1行 $\cdot$ $\mathbf{B}$ 的第2列 = $\mathbf{a}_1^\top \mathbf{b}_2$
    $c_{12} = (1 \times 8) + (2 \times 10) + (3 \times 12) = 8 + 20 + 36 = 64$

3.  **$c_{21}$ (C的第二行第一列)** = $\mathbf{A}$ 的第2行 $\cdot$ $\mathbf{B}$ 的第1列 = $\mathbf{a}_2^\top \mathbf{b}_1$
    $c_{21} = (4 \times 7) + (5 \times 9) + (6 \times 11) = 28 + 45 + 66 = 139$

4.  **$c_{22}$ (C的第二行第二列)** = $\mathbf{A}$ 的第2行 $\cdot$ $\mathbf{B}$ 的第2列 = $\mathbf{a}_2^\top \mathbf{b}_2$
    $c_{22} = (4 \times 8) + (5 \times 10) + (6 \times 12) = 32 + 50 + 72 = 154$

最后，把这些结果组合成矩阵 $\mathbf{C}$：

$$
\mathbf{C} = \begin{bmatrix} 58 & 64 \\ 139 & 154 \end{bmatrix}
$$

In [62]:
A,A.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 torch.Size([5, 4]))

In [63]:
B = torch.ones(4,3)
B,B.shape

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 torch.Size([4, 3]))

In [64]:
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

## 范数
1. 绝对值缩放
$$
f\left( \alpha \mathbf{x} \right) =|\alpha |\mathbf{x}
$$
2. 三角不等式
$$
f\left( \mathbf{x}+\mathbf{y} \right) \leqslant f\left( \mathbf{x} \right) +f\left( \mathbf{y} \right) 
$$
3. 非负
$$
f\left( \mathbf{x} \right) \geqslant 0
$$
4. 最小为$0$
$$
\forall i,\left[ \mathbf{x} \right] _i=0\leftrightarrow f\left( \mathbf{x} \right) =0
$$
### L2范数
$$
\left\| \mathbf{x} \right\| =\left\| \mathbf{x} \right\| _2=\sqrt{\sum_{i=1}^n{x_{i}^{2}}}
$$


In [65]:
u = torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

$L_1$范数:$$
\left\| \mathbf{x} \right\| _1=\sum_{i=1}^n{|x_i|}
$$


In [66]:
torch.abs(u).sum()

tensor(7.)

$L_P$ 范数
$$
\left\| \mathbf{x} \right\| _p=\left( \sum_{i=1}^n{|x_i|^p} \right) ^{\frac{1}{p}}
\\
$$
$Forbenius范数$ 是矩阵元素平方和的平方根

$$
\left\| \mathbf{X} \right\| _F=\sqrt{\sum_{i=1}^m{\sum_{j=1}^n{x_{ij}^{2}}}}
$$


In [67]:
torch.norm(torch.ones(4,9))

tensor(6.)

## 练习

### 1. 证明：一个矩阵A的转置的转置是A
$$
(\mathbf{A}^\top)^\top = \mathbf{A}
$$

**直观解释：**
矩阵的转置操作就是将其行和列进行互换。可以想象成将整个矩阵沿主对角线（从左上到右下）翻转一次。如果连续翻转两次，它自然就回到了原来的位置。

**形式化证明：**
我们通过矩阵的元素来证明。假设矩阵 $\mathbf{A}$ 是一个 $m \times n$ 的矩阵，其在第 $i$ 行第 $j$ 列的元素记为 $(\mathbf{A})_{ij}$。

1.  根据转置的定义，$\mathbf{A}^\top$ 是一个 $n \times m$ 的矩阵，其在第 $i$ 行第 $j$ 列的元素为：
    $$
    (\mathbf{A}^\top)_{ij} = (\mathbf{A})_{ji}
    $$
2.  现在对 $\mathbf{A}^\top$ 再次进行转置，得到 $(\mathbf{A}^\top)^\top$。这是一个 $m \times n$ 的矩阵。其在第 $i$ 行第 $j$ 列的元素为：
    $$
    ((\mathbf{A}^\top)^\top)_{ij} = (\mathbf{A}^\top)_{ji}
    $$
3.  结合第一步的结论，我们将 $(\mathbf{A}^\top)_{ji}$ 替换为原始矩阵 $\mathbf{A}$ 的元素，即 $(\mathbf{A})_{ij}$。
    $$
    ((\mathbf{A}^\top)^\top)_{ij} = (\mathbf{A})_{ij}
    $$
由于这个等式对所有的 $i$ 和 $j$ 都成立，因此证明了 $(\mathbf{A}^\top)^\top = \mathbf{A}$。



### 2. 证明：“它们转置的和”等于“它们和的转置”
$$
\mathbf{A}^\top + \mathbf{B}^\top = (\mathbf{A} + \mathbf{B})^\top
$$

**直观解释：**
矩阵加法是逐个元素相加的。你可以先将两个矩阵对应位置的元素相加，然后将结果矩阵进行行列互换；也可以先将两个矩阵分别进行行列互换，然后再将它们相加。由于加法和行列互换这两个操作的顺序不影响最终每个元素的值，所以结果是相同的。

**形式化证明:**
假设 $\mathbf{A}$ 和 $\mathbf{B}$ 是两个同型的 $m \times n$ 矩阵。

1.  我们先看等式右边 $(\mathbf{A} + \mathbf{B})^\top$。令 $\mathbf{C} = \mathbf{A} + \mathbf{B}$，则 $\mathbf{C}$ 的每个元素为 $(\mathbf{C})_{ij} = (\mathbf{A})_{ij} + (\mathbf{B})_{ij}$。
2.  对 $\mathbf{C}$ 进行转置，其在第 $i$ 行第 $j$ 列的元素为：
    $$
    (\mathbf{C}^\top)_{ij} = (\mathbf{C})_{ji} = (\mathbf{A})_{ji} + (\mathbf{B})_{ji}
    $$
3.  现在看等式左边 $\mathbf{A}^\top + \mathbf{B}^\top$。根据转置的定义，我们知道 $(\mathbf{A}^\top)_{ij} = (\mathbf{A})_{ji}$ 且 $(\mathbf{B}^\top)_{ij} = (\mathbf{B})_{ji}$。
4.  将这两个转置矩阵相加，得到的新矩阵在第 $i$ 行第 $j$ 列的元素为：
    $$
    (\mathbf{A}^\top + \mathbf{B}^\top)_{ij} = (\mathbf{A}^\top)_{ij} + (\mathbf{B}^\top)_{ij} = (\mathbf{A})_{ji} + (\mathbf{B})_{ji}
    $$

比较第二步和第四步的结果，可以看出两边矩阵在任意位置 $(i, j)$ 的元素都相等，因此这两个矩阵是相等的。


### 3. 给定任意方阵A, A + Aᵀ 总是对称的吗？为什么？

**是的，对于任意方阵 $\mathbf{A}$，矩阵 $\mathbf{A} + \mathbf{A}^\top$ 总是对称的。**

**解释与证明：**
首先，我们回顾一下**对称矩阵**的定义：一个方阵 $\mathbf{S}$ 如果满足其转置等于自身，即 $\mathbf{S}^\top = \mathbf{S}$，那么它就是对称矩阵。

现在，我们需要证明 $\mathbf{A} + \mathbf{A}^\top$ 满足这个定义。令一个新的矩阵 $\mathbf{C} = \mathbf{A} + \mathbf{A}^\top$。我们的目标是证明 $\mathbf{C}^\top = \mathbf{C}$。

1.  对 $\mathbf{C}$ 进行转置：
    $$
    \mathbf{C}^\top = (\mathbf{A} + \mathbf{A}^\top)^\top
    $$
2.  根据上一问证明的性质（和的转置等于转置的和），我们可以将上式展开：
    $$
    (\mathbf{A} + \mathbf{A}^\top)^\top = \mathbf{A}^\top + (\mathbf{A}^\top)^\top
    $$
3.  再根据第一问证明的性质（转置的转置等于原矩阵），我们得到：
    $$
    \mathbf{A}^\top + (\mathbf{A}^\top)^\top = \mathbf{A}^\top + \mathbf{A}
    $$
4.  由于矩阵加法满足交换律，$\mathbf{A}^\top + \mathbf{A} = \mathbf{A} + \mathbf{A}^\top$。
5.  我们发现，这个结果正是我们定义的原始矩阵 $\mathbf{C}$。

所以，我们完成了证明：
$$
\mathbf{C}^\top = \mathbf{A} + \mathbf{A}^\top = \mathbf{C}
$$
因为 $\mathbf{C}^\top = \mathbf{C}$，所以 $\mathbf{A} + \mathbf{A}^\top$ 总是一个对称矩阵。


### 4. 本节中定义了形状(2, 3, 4)的张量X。len(X)的输出结果是什么？

`len(X)` 的输出结果是 **2**。

**解释:**
在 Python 中，`len()` 函数通常返回一个对象的第一维（或最外层）的长度。对于 PyTorch 张量（或 NumPy 数组），`len()` 会返回其第 0 轴 (axis 0) 的大小。


In [68]:
import torch

# 创建一个形状为 (2, 3, 4) 的张量
X = torch.randn(2, 3, 4)

print("张量的形状:", X.shape)
print("len(X) 的输出:", len(X))

张量的形状: torch.Size([2, 3, 4])
len(X) 的输出: 2




### 5. 对于任意形状的张量X, len(X)是否总是对应于X特定轴的长度？这个轴是什么？

是的，`len(X)` **总是对应于张量 X 特定轴的长度**。

这个轴是 **第0轴 (axis=0)**。

无论是二维矩阵、三维张量还是更高维度的张量，`len()` 函数始终返回第一个维度的长度。

### 6. 运行 `A/A.sum(axis=1)`，看看会发生什么。请分析一下原因？
其中 `A = torch.arange(20).reshape(5, 4)`

运行这段代码会**引发一个运行时错误 (RuntimeError)**。

**原因分析:**
这涉及到 PyTorch/NumPy 中的**广播机制 (Broadcasting)**。当对两个形状不同的张量进行运算时，系统会尝试“广播”较小的张量，通过复制其数据使其形状与较大的张量兼容。

1.  **分析 A 的形状**:
    `A` 是一个 `5x4` 的矩阵。
    ```
    A = tensor([[ 0,  1,  2,  3],
                [ 4,  5,  6,  7],
                [ 8,  9, 10, 11],
                [12, 13, 14, 15],
                [16, 17, 18, 19]])
    A.shape -> torch.Size([5, 4])
    ```

2.  **分析 `A.sum(axis=1)` 的形状**:
    `axis=1` 表示沿着**行**对元素求和（即对每一行的所有列求和）。
    ```
    A.sum(axis=1) = tensor([ 6, 22, 38, 54, 70])
    A.sum(axis=1).shape -> torch.Size([5])
    ```
    我们得到了一个长度为5的一维张量。

3.  **广播机制如何工作**:
    当计算 `A / A.sum(axis=1)` 时，PyTorch 尝试匹配它们的形状。它从**尾部维度 (trailing dimensions)** 开始比较：
    *   `A` 的形状: `(5, 4)`
    *   `A.sum(axis=1)` 的形状: `(5)`

    PyTorch 的广播规则无法将 `(5, 4)` 和 `(5)` 对齐进行逐元素除法。尾部维度 `4` 和 `5` 不匹配，并且其中一个不为 `1`，因此无法广播。

**如何修正这个问题？**
如果我们想让每一行的元素都除以该行的总和，我们需要保持求和后的维度，使其形状变为 `(5, 1)`。这可以通过设置 `keepdim=True` 来实现。
这样，一个 `(5, 1)` 的张量就可以和 `(5, 4)` 的张量进行运算了，因为 `1` 可以被广播到 `4`。



In [69]:
import torch

A = torch.arange(20, dtype=torch.float32).reshape(5, 4)

# 这样会报错
try:
    C = A / A.sum(axis=1)
except RuntimeError as e:
    print("发生了错误:", e)

# 正确的做法
A_sum = A.sum(axis=1, keepdim=True)
print("\nA.sum(axis=1, keepdim=True) 的形状:", A_sum.shape)
# (5, 4) / (5, 1) -> (5, 4) 
# (5, 1) 的列被广播(复制)4次来匹配 (5, 4) 的形状
C_correct = A / A_sum
print("\n正确的计算结果:\n", C_correct)

发生了错误: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 1

A.sum(axis=1, keepdim=True) 的形状: torch.Size([5, 1])

正确的计算结果:
 tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])


### 7. 考虑一个具有形状(2, 3, 4)的张量，在轴0、1、2上的求和输出是什么形状？

假设张量为 `X`，形状为 `(2, 3, 4)`。在某个轴上求和，会“压缩”掉该轴，使其维度消失。

*   **在轴 `0` 上求和**: `X.sum(axis=0)`
    形状从 `(2, 3, 4)` 变为 `(3, 4)`。

*   **在轴 `1` 上求和**: `X.sum(axis=1)`
    形状从 `(2, 3, 4)` 变为 `(2, 4)`。

*   **在轴 `2` 上求和**: `X.sum(axis=2)`
    形状从 `(2, 3, 4)` 变为 `(2, 3)`。

---
### 8. 为 `linalg.norm` 函数提供3个或更多轴的张量，并观察其输出。对于任意形状的张量这个函数计算得到什么？

`torch.linalg.norm` (或其别名 `torch.norm`) 在不指定任何轴的情况下，计算的是张量中**所有元素的 L2 范数**，也称为 **Frobenius 范数** 的推广。

对于一个任意张量 $\mathbf{X}$，其计算公式为：
$$
||\mathbf{X}|| = \sqrt{\sum_{i_1, i_2, \dots, i_n} |x_{i_1, i_2, \dots, i_n}|^2}
$$
这本质上是将张量“展平”成一个长向量，然后计算这个向量的欧几里得距离（L2范数）。

**观察输出:**
无论输入张量的维度有多少（是3维、4维还是更高维），输出都是一个**标量**（0维张量），代表整个张量的范数。


**总结:** 对于任意形状的张量，`linalg.norm` 函数默认计算的是一个单一的数值，该数值是对张量中所有元素平方求和再开方的结果，衡量了张量整体的大小。

In [70]:
import torch

# 创建一个 3 轴张量 (2, 3, 4)
X_3d = torch.arange(24, dtype=torch.float32).reshape(2, 3, 4)

# 计算它的范数
norm_3d = torch.linalg.norm(X_3d)

print("3D 张量:\n", X_3d)
print("\n它的范数:", norm_3d)
print("范数的形状:", norm_3d.shape) # shape 是 torch.Size([]) 表示标量
print("-" * 20)

# 我们可以手动验证
# 先计算所有元素的平方和，然后开方
manual_norm = torch.sqrt(torch.sum(X_3d ** 2))
print("手动计算的范数:", manual_norm)
print("两次计算结果是否接近:", torch.allclose(norm_3d, manual_norm))

3D 张量:
 tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

它的范数: tensor(65.7571)
范数的形状: torch.Size([])
--------------------
手动计算的范数: tensor(65.7571)
两次计算结果是否接近: True
