# 数据操作
## 入门

In [5]:
import torch

In [7]:
#张量
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
x.shape

torch.Size([12])

`torch.numel()` 函数在 `PyTorch` 中用于返回张量（`tensor`）中元素的总数。 “`numel`” 是 “`number of elements`” 的缩写。 这是一个非常直接且常用的函数，无论张量的维度和形状如何，它都能计算出其包含的元素总量。

In [9]:
x.numel()

12

In [12]:
a = torch.randn(3,4,5)
print(a)
print(torch.numel(a))

tensor([[[-0.8993,  0.1742, -1.0669,  0.8057,  1.6334],
         [-1.4314,  0.5190, -0.7845,  1.4581, -1.2370],
         [-1.7109, -1.1460, -0.4439,  1.2577,  0.5577],
         [ 1.6739, -2.0033, -0.6388,  0.9141, -0.2859]],

        [[ 0.3324, -1.4445,  0.5483,  0.2540, -0.5385],
         [-1.6381, -0.3854, -1.9881, -0.7307, -0.4182],
         [-1.9368, -0.4709, -1.2271,  1.0843,  0.7250],
         [-0.6483,  1.6873,  1.8091,  0.1716, -1.7271]],

        [[-0.4745,  0.2260,  0.5525,  1.5142, -0.1269],
         [-0.0301,  0.0693,  0.2105,  0.6392,  0.3694],
         [ 1.3641, -1.6293, -2.4540, -1.1857,  0.5656],
         [-0.7967, -0.4917, -0.8445, -0.4807,  0.2793]]])
60


In [17]:
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [18]:
X_ = x.reshape(3,-1) #用-1自动推导
X_

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [19]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
# 正态分布
torch.randn(3,4)

tensor([[-0.5790,  1.8698,  0.6541, -0.0435],
        [ 0.7829,  0.0089,  1.9323,  0.2683],
        [-0.1407,  0.4052,  1.4851, -0.2203]])

In [22]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## 运算符

In [26]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,  2,2,2])
x+y,x-y,x*y,x/y,x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [27]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [29]:
X = torch.arange(12,dtype=torch.float32).reshape(3,4)
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
X,Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

In [30]:
torch.cat((X,Y),dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [31]:
torch.cat((X,Y),dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [32]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [34]:
X.sum(),X.sum(dim=0),X.sum(dim=1)

(tensor(66.), tensor([12., 15., 18., 21.]), tensor([ 6., 22., 38.]))

## 广播机制

In [35]:
a = torch.arange(3).reshape(3,1)
b = torch.arange(2).reshape(1,2)

In [36]:
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [37]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 索引&切片

In [38]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [39]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [40]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [41]:
X[1,2]=9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [42]:
X[0:2,:]=12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 节省内存

In [43]:
Y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [45]:
before = id(Y)
before

2492322812112

In [46]:
Y = Y+X
id(Y)

2492329182704

In [47]:
Z = torch.zeros_like(Y)
print("id(Z):",id(Z))
Z[:]=X+Y
print("id(Z):",id(Z))

id(Z): 2492329268848
id(Z): 2492329268848


In [48]:
before = id(X)
before

2492322812496

In [49]:
X+=Y

In [50]:
id(X)

2492322812496

## 转换为其他python对象

In [51]:
A = x.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [53]:
a = torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [54]:
X,Y

(tensor([[26., 25., 28., 27.],
         [25., 26., 27., 28.],
         [20., 21., 22., 23.]]),
 tensor([[14., 13., 16., 15.],
         [13., 14., 15., 16.],
         [12., 12., 12., 12.]]))

In [55]:
X == Y,X>Y,X<Y

(tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

## 广播机制
广播的核心规则
> 当对两个张量进行运算时，PyTorch 会从尾部维度开始比较它们的形状。广播机制能够成功执行，需要满足以下两个条件之一：

- 两个张量在当前维度上的大小相等。
- 其中一个张量在当前维度上的大小为 1。
如果这两个条件都不满足，系统就会报错。

In [56]:
import torch

# 创建一个 2x3x4 的三维张量
X = torch.arange(24).reshape(2, 3, 4)

print("原始张量 X 的形状:", X.shape)
print("原始张量 X:\n", X)

原始张量 X 的形状: torch.Size([2, 3, 4])
原始张量 X:
 tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [57]:
# 创建一个标量
scalar = 100

# 运算
result = X + scalar

print("结果张量的形状:", result.shape)
print("结果张量:\n", result)

结果张量的形状: torch.Size([2, 3, 4])
结果张量:
 tensor([[[100, 101, 102, 103],
         [104, 105, 106, 107],
         [108, 109, 110, 111]],

        [[112, 113, 114, 115],
         [116, 117, 118, 119],
         [120, 121, 122, 123]]])


In [59]:
# 创建一个 2x1x4 的张量
Y = torch.arange(8).reshape(2, 1, 4) * 10

print("张量 Y 的形状:", Y.shape)
print("张量 Y:\n", Y)
print("张量 X 的形状:", X.shape)
print("张量 X:\n", X)

# 运算
result = X + Y
print("\n结果张量的形状:", result.shape)
print("结果张量:\n", result)

张量 Y 的形状: torch.Size([2, 1, 4])
张量 Y:
 tensor([[[ 0, 10, 20, 30]],

        [[40, 50, 60, 70]]])
张量 X 的形状: torch.Size([2, 3, 4])
张量 X:
 tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

结果张量的形状: torch.Size([2, 3, 4])
结果张量:
 tensor([[[ 0, 11, 22, 33],
         [ 4, 15, 26, 37],
         [ 8, 19, 30, 41]],

        [[52, 63, 74, 85],
         [56, 67, 78, 89],
         [60, 71, 82, 93]]])


In [60]:
# 创建一个形状不兼容的张量 (2, 3, 2)，注意最后一个维度是 2，不是 4 也不是 1
Y_fail = torch.randn(2, 3, 2)

try:
    result = X + Y_fail
except RuntimeError as e:
    print("广播失败，错误信息:")
    print(e)

广播失败，错误信息:
The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 2
